### ISSUE TITLE
infoWindowが全部テスト用画像なので差し替える

### ISSUE THREAD

**Issue by siida36** [asaka2-alb/smart-sauna-map-back#11]
https://github.com/asaka2-alb/smart-sauna-map-front/issues/4

**Comment by taisei-watanabe** [comment]
## 背景

検索後にマップに出現するサウナアイコンをクリックすると PopupWindow が表示される。

## 課題

この Window 中の画像が現在はすべてサウナしきじになっている。
サウナの温度なども現在は適当なものを入力している。

## 目的

PopupWindow の表示内容を適切なものにすること。

## 提案

- サウナしきじの画像ではなく、本当にそのサウナの画像を表示するようにする。
- サウナの温度なども適切なものを取得する。

**Comment by taisei-watanabe** [comment]
## 背景

検索後にマップに出現するサウナアイコンをクリックすると PopupWindow が表示される。

## 課題

この Window 中の画像が現在はすべてサウナしきじになっている。
サウナの温度なども現在は適当なものを入力している。

## 目的

PopupWindow の表示内容を適切なものにすること。

## 提案

- サウナしきじの画像ではなく、本当にそのサウナの画像を表示するようにする。
- サウナの温度なども適切なものを取得する。
