### ISSUE TITLE
検索結果に引っかからないときの振る舞いを整理する

### ISSUE THREAD

**Issue by siida36** [asaka2-alb/smart-sauna-map-back#2]
## 問題

- 検索結果に引っかからなかった場合、エラーを吐いてこける

## 目的

- エラーハンドリングを追加し、エラー時に異常終了しないようにする
- 何かしらユーザに伝える方法を実装する

## 仕様

- エラー時にフロント側に返す値
  - 現状: 
    - 正常時には `{"lat": xxx, "lng": yyy}` を返す
    - 異常時には新宿の緯度経度を返す
  - 修正内容:
    - 正常時には `{"lat": xxx, "lng": yyy}, 200` を返す
    - 異常時には `{"lat": 新宿緯度, "lng": 新宿経度}, 404` を返す
      - 異常時に返す緯度経度へのこだわりは特にない

## 受け入れ条件

- [ ] サーバ側でテストを通す
- [ ] フロント側でもテストを通す
  - [フロント側Issueのリンク](https://github.com/asaka2-alb/smart-sauna-map-front/issues/11)

**Comment by siida36** [comment]
上記PRではエラー時に異常終了しないようにする機能しか実装していない。
ユーザに伝える方法を実装する箇所はフロント側に横断する機能であるためだった。

それでは目的を達成できていない。
よってフロント側でもこの問題に関するイシューを立て、両サイドで修正と確認を実施してからマージするように進める。

**Comment by siida36** [comment]
>>1 に `仕様` `受け入れ条件` を追加

**Comment by taisei-watanabe** [comment]
@siida36 
- [flask: アプリケーションのエラーの処理](https://msiz07-flask-docs-ja.readthedocs.io/ja/latest/errorhandling.html)
